services:
  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - todo-network
    container_name: "ktor-web-service"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    container_name: "postgres-service"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - todo-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 1s

networks:
  todo-network:
    driver: bridge


